[build]
  command = "npm install && npm run build"
  publish = "src/views"
  functions = "functions"

[[redirects]]
  from = "/test"
  to = "src/views/index.html"
  status = 200

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/server/api"
  status = 200
